### ISSUE TITLE
Migrate to requests

### ISSUE THREAD

**Issue by 0x48piraj** [SubhrajitPrusty/unsplash-download#3]
- Using browser to view a website is a bad idea. (heavy framework)
- requests with bs4 gels great.
- Requests gives more flexibility to the developer

**Comment by SubhrajitPrusty** [comment]
Earlier when I started the project, I started with requests. But it failed to catch the images since the images were being dynamically loaded. Seems like it can be done with requests now.

If you use requests, the same photos will be downloaded for a given tag almost every time (while no new submissions have been made)
With a browser module, we can scroll down to load more images.

**Comment by 0x48piraj** [comment]
No code is there for scrolling. Anyway, closing this.
